spring:
  profiles:
    active: prod
  application:
    name: 'Redis Slack Bot'
  main:
    allow-bean-definition-overriding: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    context-path: /
  port: 9723
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  pattern:
    console: "{\"time\": \"%d{yyyy-MM-dd'T'HH:mm:ss}Z\", \"level\": \"%p\", \"agent-name\": \"%X{x-agentname}\", \"correlation-id\": \"%X{x-correlationid}\", \"executor-user\": \"%X{x-executor-user}\", \"remote-host\": \"%X{x-remote-host}\", \"request-path\":\"%X{Request-Path}\", \"user-agent\":\"%X{User-Agent}\", \"source\":\"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{10}){'[\r\n]+', '\n'}%nopex\"}%n"
  level:
    com.trendyol: INFO

redis:
  host: ${REDIS_HOST}
  password: ${REDIS_PASSWORD}
  port: 6379

slack:
  token: ${NOTIFY_TOKEN}
  channelId: ${CHANNEL_ID}
  username: "Redis Slack Bot"